### ISSUE TITLE
Add support for Batch operation

### ISSUE THREAD

**Issue by lillo42** [justeattakeaway/JustSaying#1095]
Hi,

Today AWS has support for batch operation by sending 10 by 10 messages for [SNS ](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-sns-supports-publishing-batches-messages-single-api-request/) and [SQS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html), and I think it would be nice have support for it. Today I'm doing it send message by message; I guess, if we have it, I could reduce my AWS call and speed up my API/Lambda.

**Comment by martincostello** [comment]
Resolved by #1335.
