### ISSUE TITLE
Improve the Examples to include Middlewares?

### ISSUE THREAD

**Issue by GuilhermeMorais** [justeattakeaway/JustSaying#1106]
Hello guys,

I was looking at the code samples, hoping to find any example of how to add/create a middleware. The documentation is quite vague about that https://justeat.gitbook.io/justsaying/subscriptions/middleware. Is it possible to add a simple example for it? 

Kind Regards

**Comment by martincostello** [comment]
I think what you're looking for is documented in [this page](https://justeat.gitbook.io/justsaying/subscriptions/middleware/custom-middleware) which is linked to in the left-hand menu from the page you linked to, but I agree that it could be made more prominent/discoverable.

![image](https://user-images.githubusercontent.com/1439341/208624025-932e4533-9fe7-4097-a14a-46af669d7fd5.png)

**Comment by georgearnall** [comment]
+1 for a code sample. It looks like that documentation is woefully out of date

**Comment by gkinsman** [comment]
There are some more detailed examples of middleware use cases on the internal JET GitHub if someone wanted to share them (as I no longer work there). 

To solve your immediate issue @georgearnall, be sure to call UseDefaults before/after your own so that they're included. You can also use interrogation to inspect middleware chains to see what's going on under the covers.

**Comment by adammorr** [comment]
I'm going to start pulling in your examples @gkinsman so will update this issue when that's moving

**Comment by adammorr** [comment]
👋 we've added a sample app to the library now which can be found [here](https://github.com/justeattakeaway/JustSaying/tree/main/samples/src/JustSaying.Sample.Middleware)

**Comment by adammorr** [comment]
Hey @GuilhermeMorais let us know if the examples are sufficient enough to close out the issue, otherwise we'll see how else we can help, thanks!
