### ISSUE TITLE
DOCS: Middleware documentation is out of date, and does not reflect how to use

### ISSUE THREAD

**Issue by mgoodfellow** [justeattakeaway/JustSaying#1331]
Please see: https://github.com/justeattakeaway/JustSaying/pull/1328#issuecomment-1919487564

I couldn't find where the documentation is written otherwise I would submit a PR to update the docs.

## Updates required

https://justeat.gitbook.io/justsaying/subscriptions/middleware

Changes required
* The comment about "These defaults cannot be removed" needs to be removed.
* Ordering information isn't quite right, as the `HandlerInvocationMiddleware` doesn't need to be innermost depending on your configuration
* Code sample needs updating to reflect sample: https://github.com/justeattakeaway/JustSaying/tree/main/samples/src/JustSaying.Sample.Middleware (`UseDefaults<>`) - It should also link to this sample

https://justeat.gitbook.io/justsaying/subscriptions/middleware/custom-middleware

Changes required
* I think it should be repeated that if you setup custom middleware you are required to make sure you call `UseDefaults<>` to fully configure your pipeline

**Comment by martincostello** [comment]
The docs are [here in a different branch](https://github.com/justeattakeaway/JustSaying/tree/docs/docs). If you do a PR targeting that branch then they'll get updated 👍
