### ISSUE TITLE
System.FormatException when MessageAttributes contains type number

### ISSUE THREAD

**Issue by codrinandronic** [justeattakeaway/JustSaying#1556]
**Describe the bug**
When an SQS message contains MessageAttributes with Type Number, an exception of type System.FormatException is thrown when the message is picked up from the queue.

**Steps To reproduce**
Send an SQS message coining the following MessageAttributes:
"MessageAttributes" : {
    "TotalValue" : {"Type":"Number","Value":"100"}
  }

**Expected behaviour**
Message should be picked up with no exception.

**Actual behaviour**
The following exception is thrown:
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at JustSaying.Messaging.MessageSerialization.NewtonsoftSerializer.GetMessageAttributes(String message) in /_/src/JustSaying/Messaging/MessageSerialization/NewtonsoftSerializer.cs:line 54
   at JustSaying.Messaging.MessageSerialization.MessageSerializationRegister.DeserializeMessage(String body) in /_/src/JustSaying/Messaging/MessageSerialization/MessageSerializationRegister.cs:line 45
   at JustSaying.AwsTools.MessageHandling.Dispatch.MessageDispatcher.DeserializeMessage(IQueueMessageContext messageContext, CancellationToken cancellationToken) in /_/src/JustSaying/AwsTools/MessageHandling/Dispatch/MessageDispatcher.cs:line 79

**System information:**
 - OS: Windows 11
 - Library Version 7.0.0 and above
 - .NET version 8

**Additional context**
Both SystemTextJsonSerializer and NewtonsoftSerializer implementation of GetMessageAttributes() handle only String data types. Everything else is considered Binary. But AWS documentation specifies that Message Attributes can have 4 data types: string, number, binary and custom which should be handled.

**Comment by martincostello** [comment]
From [`MessageAttributeValue.DataType`](https://github.com/aws/aws-sdk-net/blob/ad13fd46500b624f3e39190a8ed9f32633ca0559/sdk/src/Services/SQS/Generated/Model/MessageAttributeValue.cs#L89-L106):

> Amazon SQS supports the following logical data types: <c>String</c>, <c>Number</c>,
> and <c>Binary</c>. For the <c>Number</c> data type, you must use <c>StringValue</c>.

We need to add support for `Number` in at least these two places:

https://github.com/justeattakeaway/JustSaying/blob/56b88772b267c7baf998890fb30a261a86d2013a/src/JustSaying/Messaging/MessageSerialization/NewtonsoftSerializer.cs#L64-L78

https://github.com/justeattakeaway/JustSaying/blob/56b88772b267c7baf998890fb30a261a86d2013a/src/JustSaying/Messaging/MessageSerialization/SystemTextJsonSerializer.cs#L71-L81
